config/routes.rb
GaMapQuery::Application.routes.draw do
  resources :locations

  devise_for :users

  root :to => 'locations#home'

  post '/send_email' => 'locations#send_email'
  

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude

	geocoded_by :address
	after_validation :geocode, :if => :address_changed?


  validates_presence_of :address
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authenticate_user!, :except => [:home, :send_email]

  # GET /locations
  # GET /locations.json
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 1500, :order => :distance)
    else
      @locations = Location.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end

  end


  def home

    @location = Location.near(params[:search], 1500, :order => :distance).first
    @locationlist = Location.near(params[:search], 1500, :order => :distance)
    @locationsall =  Location.all

    @search = params[:search]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  def send_email
    @search = params[:search]
    @to = params[:to]
    @location = Location.near(@search, 1500, :order => :distance).first
    Contactme.form_email(@to, @search).deliver
  end



  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/common/_address.html.erb
<%= @location.address %>

app/views/common/_directions.html.erb
<%  file = open("http://maps.googleapis.com/maps/api/directions/json?origin=#{URI.escape(@search)}&destination=#{URI.escape(@location.address)}&sensor=true") %>
  <% @results = JSON.load(file.read) %>
<!--<%= @directions = @results["routes"][0]["legs"][0] %> -->
  <!--    ["steps"][0]["html_instructions"] -->

<ul>
 <% @results["routes"][0]["legs"][0]["steps"].each_with_index do |direction, index| %>
	<% if index == @results["routes"][0]["legs"][0]["steps"].size - 1 %>
		<li><%= direction["html_instructions"].html_safe %></li> 
	<% else %>	
		<li><%= direction["html_instructions"].html_safe %> for 
		<%= direction["distance"]["text"].html_safe %></li>
	<% end %>
<% end %>
</ul>


	

app/views/common/_distance.html.erb
<%= @location.distance_to(@search).round(2) %>  

app/views/common/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/common/_googlebackgroundmap.html.erb
<% if @location %>
<% address = @location.address %>
<% else %>
<% address = "10012" %>
<% end %>

<iframe id="gmap" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=<%= address %>&amp;ie=UTF8&amp;z=14&amp;output=embed&amp;iwloc=near" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="425" height="350"></iframe>

app/views/common/_searchbar.html.erb
<% if @location %>
      <div class="query">      
<% else %>
      <div class="noquery">    
<% end %>

<h1>T<img src="assets/google-marker.png" width="23px" />ke me to <img class="image_ga_logo" src="assets/GA_logo_1797cog.png" width="35px" /></h1>



 <%= form_tag root_path,:method => :get do %>
  <%= text_field_tag :search, params[:search] , :id => "geocomplete"%>
  <%= submit_tag "Search", :name => 'button' , :class => "btn btn-success", :id => "find" %>

          <!-- <input id="find" type="button" value="find" /> -->

<% end %>
      </div>


<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<script src="http://ubilabs.github.io/geocomplete/jquery.geocomplete.js"></script>
<script src="http://ubilabs.github.io/geocomplete/examples/logger.js"></script>

<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<script src="http://ubilabs.github.io/geocomplete/jquery.geocomplete.js"></script>
<script src="http://ubilabs.github.io/geocomplete/examples/logger.js"></script>


<script>
  $(function(){
    
    $("#geocomplete").geocomplete()
      .bind("geocode:result", function(event, result){
        $.log("Result: " + result.formatted_address);
      })
      .bind("geocode:error", function(event, status){
        $.log("ERROR: " + status);
      })
      .bind("geocode:multiple", function(event, results){
        $.log("Multiple: " + results.length + " results found");
      });
    
    $("#find").click(function(){
      $("#geocomplete").trigger("geocode");
    });
    
    
    // $("#examples a").click(function(){
    //   $("#geocomplete").val($(this).text()).trigger("geocode");
    //   return false;
    // });
    
  });
</script>


<script type="text/javascript">
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<!--
<script type="text/javascript">
  try {
    var pageTracker = _gat._getTracker("UA-57649-7");
    pageTracker._trackPageview();
  } catch(err) {}
</script>


http://ubilabs.github.io/geocomplete/examples/simple.html
view-source:http://ubilabs.github.io/geocomplete/examples/simple.html
http://ubilabs.github.io/geocomplete/

-->

app/views/contactme/form_email.html.erb
<p>	From <%= @search %> to your closest GA at <%= @location.address %>, here are the directions: </p>

<p><%= render 'common/directions' %></p>
<p><%= render 'common/distance' %> miles total</p>

<p>Start hitting the books on Ruby!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Take Me To GA</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'common/googlebackgroundmap' %>
  
<% if @location %>
  <div id="outer-container-query"> 
<% else %>
  <div id="outer-container-noquery">
<% end %>

  
    <div id="inner-container">

    <%= yield %>
    
    </div>
  </div>
</body>
</html>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'common/form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/home.html.erb
<%= render 'common/searchbar' %>


 <% if @location %>


<div id="bodycontent">
<span class="span5">


<p class="directions"><h2>Directions</h2></p>
<p><%= render 'common/directions' %></p>

<br>

<p class="distance"><h2>Distance</h2></p>
<p class="marginleftindent">     <%= render 'common/distance' %> miles</p>

<br>

 <p class="email"><h2>Email me Info</h2></p>
<form action='/send_email' method='post'>
  <div><input type='hidden' name="search" value="<%= params[:search] %>"></div>
  <div class="styleindent"><input type='email' name='to' placeholder='email address'> <%= submit_tag 'Send' , :class => "btn btn-success" %></div>
</form>








</span>


<span class=" span5">
<p class="destinationmap"><h2>GA Location</h2></p>
<p class="marginleftindent"><%= render 'common/address' %></p>
<p class="marginleftindent"><%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@location.latitude}%2C#{@location.longitude}&zoom=14&size=400x400&sensor=false", :class => "roundedcorners" %>


<br>
<br>

<p class="origindestinationmap"><h2>Driving Map</h2></p>
<!-- w h
425 350 original -->
<p class="marginleftindent"><iframe class="roundedcorners" height="375" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=d&amp;source=s_d&amp;saddr=<%= params[:search] %>&amp;daddr=<%= @location.address %>&amp;hl=en&amp;z=6&amp;output=embed"></iframe><br /></p>

<br>
<br>
</span>
</div>




<% end %>

app/views/locations/index.html.erb
<h1 class="marginleftindent">Listing locations</h1>
<%= form_tag locations_path,:method => :get do %>
<p>
  <%= text_field_tag :search, params[:search], :class => "marginleftindent" %>
  <%= submit_tag "Search for Locations", :name => nil %>
</p>
<% end %>

<table class="marginleftindent">
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  <!--  <th><%= "Distance from #{params[:search]}" %></th>  -->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.address %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
<!--    <td><%= location.distance_to(params[:search]) > 0 ?  location.distance_to(params[:search]) : "0" %></td>


    <td><a href="locations/<%= location.id %>?q=<%= params[:search] %>">Show</a>
</td> -->
    <td> <%= link_to 'Show', location %></td>

    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path , :class => "marginleftindent" %>
<p>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'common/form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/send_email.html.erb
<h3 class="marginleftindent">
	An email was sent to <%= @to %> with the address, directions, and distance to your closest GA!  Start studying Ruby before your class session starts!
</h3>

<p class="marginleftindent"><%= link_to 'Back to Search', '/' %></p>

app/views/locations/show.html.erb
<p id="notice" class="marginleftindent"><%= notice %></p>
<!--<%= params.inspect %>
<%= params[:q].inspect %>

  <%= @location.inspect %> -->

<p class="marginleftindent">
  <b>Address:</b>
  <%= @location.address %>
</p>

<p class="marginleftindent">
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p class="marginleftindent">
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>	

<p class="marginleftindent">	

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@location.latitude}%2C#{@location.longitude}&zoom=14&size=400x400&sensor=false" %>
</p>

<h3 class="marginleftindent">Nearby</h3>
<ul>
<% for location in @location.nearbys(500)%>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %>) miles</li>
<% end %>
</ul>

<p class="marginleftindent">
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>
</p>